In [12]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/ANN diabetes/data/diabetes_latih.csv')

X_train = df.values
X_train = np.delete(X_train,8,axis=1)

y_train = df['Outcome'].values

df = pd.read_csv('/content/drive/MyDrive/ANN diabetes/data/diabetes_uji.csv')

X_test = df.values
X_test = np.delete(X_test,8,axis=1)

y_test = df['Outcome'].values

print(X_test)
df.head()

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  4.    114.     65.    ...  21.9     0.432  37.   ]
 [  9.    156.     86.    ...  34.3     1.189  42.   ]
 [  1.    153.     82.    ...  40.6     0.687  23.   ]]


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
from sklearn.preprocessing import MinMaxScaler

X_train = MinMaxScaler().fit_transform(X_train)
X_test = MinMaxScaler().fit_transform(X_test)

print(X_train)

[[0.47058824 0.94472362 0.68421053 ... 0.71385991 0.02519214 0.36666667]
 [0.41176471 0.7638191  0.77192982 ... 0.74515648 0.11058924 0.25      ]
 [0.11764706 0.49748744 0.45614035 ... 0.36661699 0.23868488 0.        ]
 ...
 [0.29411765 0.6080402  0.63157895 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.52631579 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.61403509 ... 0.45305514 0.10119556 0.03333333]]


In [6]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=3,learning_rate_init=0.1,max_iter=100)

clf.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=3, learning_rate_init=0.1, max_iter=100)

In [7]:
y_pred = clf.predict(X_test)

In [8]:
from sklearn.metrics import accuracy_score

round(accuracy_score(y_test,y_pred),3)

0.721

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               154 non-null    int64  
 1   Glucose                   154 non-null    int64  
 2   BloodPressure             154 non-null    int64  
 3   SkinThickness             154 non-null    int64  
 4   Insulin                   154 non-null    int64  
 5   BMI                       154 non-null    float64
 6   DiabetesPedigreeFunction  154 non-null    float64
 7   Age                       154 non-null    int64  
 8   Outcome                   154 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 11.0 KB
